# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        # MainWindow.resize()
        MainWindow.setFixedSize(390, 501)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 391, 501))
        self.widget.setStyleSheet("background-color: #BBF4FF;\n")
        self.widget.setObjectName("widget")
        self.key_bs = QtWidgets.QPushButton(self.widget)
        self.key_bs.setGeometry(QtCore.QRect(110, 90, 81, 71))
        self.key_bs.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_bs.setStyleSheet("background-color: #D90000;\n"
"border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"color: white;;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_bs.setObjectName("key_bs")
        self.key_6 = QtWidgets.QPushButton(self.widget)
        self.key_6.setGeometry(QtCore.QRect(200, 250, 81, 71))
        self.key_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_6.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_6.setObjectName("key_6")
        self.key_clear = QtWidgets.QPushButton(self.widget)
        self.key_clear.setGeometry(QtCore.QRect(20, 90, 81, 71))
        self.key_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_clear.setStyleSheet("background-color: #D90000;\n"
"border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"color: white;;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_clear.setObjectName("key_clear")
        self.key_change_sign = QtWidgets.QPushButton(self.widget)
        self.key_change_sign.setGeometry(QtCore.QRect(200, 90, 81, 71))
        self.key_change_sign.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_change_sign.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #007DF5;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_change_sign.setObjectName("key_change_sign")
        self.key_add = QtWidgets.QPushButton(self.widget)
        self.key_add.setGeometry(QtCore.QRect(290, 90, 81, 71))
        self.key_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_add.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #007DF5;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_add.setObjectName("key_add")
        self.key_8 = QtWidgets.QPushButton(self.widget)
        self.key_8.setGeometry(QtCore.QRect(110, 330, 81, 71))
        self.key_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_8.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_8.setObjectName("key_8")
        self.key_divide = QtWidgets.QPushButton(self.widget)
        self.key_divide.setGeometry(QtCore.QRect(290, 330, 81, 71))
        self.key_divide.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_divide.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #007DF5;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_divide.setObjectName("key_divide")
        self.key_2 = QtWidgets.QPushButton(self.widget)
        self.key_2.setGeometry(QtCore.QRect(110, 170, 81, 71))
        self.key_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_2.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_2.setObjectName("key_2")
        self.key_0 = QtWidgets.QPushButton(self.widget)
        self.key_0.setGeometry(QtCore.QRect(110, 410, 81, 71))
        self.key_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_0.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_0.setObjectName("key_0")
        self.key_5 = QtWidgets.QPushButton(self.widget)
        self.key_5.setGeometry(QtCore.QRect(110, 250, 81, 71))
        self.key_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_5.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_5.setObjectName("key_5")
        self.key_calc = QtWidgets.QPushButton(self.widget)
        self.key_calc.setGeometry(QtCore.QRect(200, 410, 171, 71))
        self.key_calc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_calc.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_calc.setObjectName("key_calc")
        self.key_multiply = QtWidgets.QPushButton(self.widget)
        self.key_multiply.setGeometry(QtCore.QRect(290, 250, 81, 71))
        self.key_multiply.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_multiply.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #007DF5;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_multiply.setObjectName("key_multiply")
        self.key_3 = QtWidgets.QPushButton(self.widget)
        self.key_3.setGeometry(QtCore.QRect(200, 170, 81, 71))
        self.key_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_3.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_3.setObjectName("key_3")
        self.key_dot = QtWidgets.QPushButton(self.widget)
        self.key_dot.setGeometry(QtCore.QRect(20, 410, 81, 71))
        self.key_dot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_dot.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_dot.setObjectName("key_dot")
        self.key_substract = QtWidgets.QPushButton(self.widget)
        self.key_substract.setGeometry(QtCore.QRect(290, 170, 81, 71))
        self.key_substract.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_substract.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #007DF5;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_substract.setObjectName("key_substract")
        self.key_7 = QtWidgets.QPushButton(self.widget)
        self.key_7.setGeometry(QtCore.QRect(20, 330, 81, 71))
        self.key_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_7.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_7.setObjectName("key_7")
        self.key_1 = QtWidgets.QPushButton(self.widget)
        self.key_1.setGeometry(QtCore.QRect(20, 170, 81, 71))
        self.key_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_1.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_1.setObjectName("key_1")
        self.key_4 = QtWidgets.QPushButton(self.widget)
        self.key_4.setGeometry(QtCore.QRect(20, 250, 81, 71))
        self.key_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_4.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_4.setObjectName("key_4")
        self.key_9 = QtWidgets.QPushButton(self.widget)
        self.key_9.setGeometry(QtCore.QRect(200, 330, 81, 71))
        self.key_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.key_9.setStyleSheet("border: 1px solid #0A6972;\n"
"border-radius: 10%;\n"
"background-color: #0F8894;\n"
"color: white;\n"
"font-size:24px;\n"
"font-family:arial;")
        self.key_9.setObjectName("key_9")
        self.output_field = QtWidgets.QTextEdit(self.widget)
        self.output_field.setGeometry(QtCore.QRect(20, 20, 351, 61))
        self.output_field.setStyleSheet("border: 2px solid #0A6972;border-radius: 10px;background-color:#222;color:#ddd;")
        self.output_field.setObjectName("output_field")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        MainWindow.setWindowIcon(QtGui.QIcon('icon.ico'))
        self.key_bs.setText(_translate("MainWindow", "BS"))
        self.key_6.setText(_translate("MainWindow", "6"))
        self.key_clear.setText(_translate("MainWindow", "C"))
        self.key_change_sign.setText(_translate("MainWindow", "+/-"))
        self.key_add.setText(_translate("MainWindow", "+"))
        self.key_8.setText(_translate("MainWindow", "8"))
        self.key_divide.setText(_translate("MainWindow", "/"))
        self.key_2.setText(_translate("MainWindow", "2"))
        self.key_0.setText(_translate("MainWindow", "0"))
        self.key_5.setText(_translate("MainWindow", "5"))
        self.key_calc.setText(_translate("MainWindow", "="))
        self.key_multiply.setText(_translate("MainWindow", "x"))
        self.key_3.setText(_translate("MainWindow", "3"))
        self.key_dot.setText(_translate("MainWindow", "."))
        self.key_substract.setText(_translate("MainWindow", "-"))
        self.key_7.setText(_translate("MainWindow", "7"))
        self.key_1.setText(_translate("MainWindow", "1"))
        self.key_4.setText(_translate("MainWindow", "4"))
        self.key_9.setText(_translate("MainWindow", "9"))
        self.output_field.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">0</span></p></body></html>"))
